const ConstantString = {
  AUTH_TEMPLATE_BACKGROUND_TITLE: "Welcome back to MCL Global",
  AUTH_TEMPLATE_BACKGROUND_DESCRIPTION:
    "Empowering agents to manage leads, access insights, and stay connected. Sign in to continue delivering excellence.",
  AUTH_SIGN_IN_TITLE: "Agent Sign In",
  AUTH_SIGN_IN_SUBTITLE: "Access your MCL Global agent portal",
  AUTH_SIGN_IN_FORGOT_PASSWORD: "Forgot Password?",
  AUTH_SIGN_IN_BUTTON: "Sign In",
  AUTH_SIGN_IN_TAGLINE: "New to MCL Global? Contact admin for account creation",
  AUTH_SIGN_IN_EMAIL_FIELD_LABLE: "Email",
  AUTH_SIGN_IN_PASSWPORD_FIELD_LABLE: "Password",
  PLATFORM_TYPE: "Agency Account",
  PLATFORM_TYPE_DESCRIPTION: "Account Management",
  PLATFORM_ACCOUNT_STATUS: "Account Status",
  PLATFORM_ACCOUNT_STATUS_APPROVED: "Approved",
  PLATFORM_ACCOUNT_STATUS_REJECTED: "Account Status",
  PLATFORM_ACCOUNT_STATUS_PENDING: "Account Status",
  AGREEMENT_SCREEN_TITLE: "Partner Onboarding",
  AGREEMENT_SCREEN_SUBTITLE: "Agreement Submission",
  AGREEMENT_SCREEN_STEPPER_ONE: "Account Created",
  AGREEMENT_SCREEN_STEPPER_TWO: "Upload Agreement",
  AGREEMENT_SCREEN_STEPPER_THREE: "Approved",
  AGREEMENT_SCREEN_CARD_TITLE: "Account Under Review",
  AGREEMENT_SCREEN_CARD_DESCRIPTION:
    "Your account has been submitted for review. Please upload the signed agreement to proceed with the onboarding process.",
  AGREEMENT_SCREEN_UPLOAD_CARD_TITLE: "Agreement PDF Upload *",
  AGREEMENT_SCREEN_UPLOAD_CARD_DESCRIPTION:
    "Choose a file or drag & drop it here",
  AGREEMENT_SCREEN_UPLOAD_CARD_HELPER: "PDF files only, up to 10MB",
  AGREEMENT_SCREEN_UPLOAD_CARD_BUTTON_TEXT: "Browse File",
  AGREEMENT_SCREEN_DOWNLOAD_CONTRACT: "Download Contract",
  AGREEMENT_SCREEN_DOWNLOAD_CONTRACT_PATH: "/contract/Contract.docx",
  AGREEMENT_SCREEN_SUBMIT_AGREEMENT: "Submit Agreement",
  DASHBOARD_WELCOME_BOARD_TITLE: "Welcome back,",
  DASHBOARD_WELCOME_BOARD_DESCRIPTION:
    "Here's what's happening with your agency today",
  DASHBOARD_WELCOME_BOARD_APPLICATION_TITLE: "Total Applications",
  DASHBOARD_STATS_CARD_TITLE_1: "Active Applications",
  DASHBOARD_STATS_CARD_TITLE_2: "Pending Review",
  DASHBOARD_STATS_CARD_TITLE_3: "Approved",
  DASHBOARD_STATS_CARD_TITLE_4: "Rejected",
  DASHBOARD_ACCOUNT_SETTINGS_TITLE: "Account settings",
  DASHBOARD_ACCOUNT_SETTINGS_SUBTITLE:
    "Manage your account preferences and security",
  DASHBOARD_ACCOUNT_SETTINGS_BUTTON_TITLE_1: "Change Password",
  DASHBOARD_ACCOUNT_SETTINGS_BUTTON_TITLE_2: "Security Settings",
  DASHBOARD_ACCOUNT_SETTINGS_BUTTON_TITLE_3: "Terms and Condition",
  DASHBOARD_ACCOUNT_SETTINGS_BUTTON_TITLE_4: "Privacy Policy",
  DASHBOARD_ACCOUNT_SETTINGS_BUTTON_TITLE_5: "Terminate Account",
  DASHBOARD_ACCOUNT_SETTINGS_BUTTON_TITLE_6: "Log Out",
  DASHBOARD_ACCOUNT_DETAILS_TITLE: "Account Details",
  DASHBOARD_ACCOUNT_DETAILS_SUBTITLE: "View your account detaisl",
  DASHBOARD_ACCOUNT_DETAILS_TITLE_1: "Name:",
  DASHBOARD_ACCOUNT_DETAILS_TITLE_2: "Username:",
  DASHBOARD_ACCOUNT_DETAILS_TITLE_3: "Email:",
  DASHBOARD_ACCOUNT_DETAILS_TITLE_4: "Password:",
};

export default ConstantString;
