# SSH-based deployment instead of FTP
- name: RSYNC Deploy
  uses: burnett01/rsync-deployments@5.2.3
  with:
    switches: -avzr --delete
    path: ./
    remote_path: ${{ secrets.REMOTE_PATH }}
    remote_host: ${{ secrets.REMOTE_HOST }}
    remote_user: ${{ secrets.REMOTE_USER }}
    remote_key: ${{ secrets.REMOTE_KEY }}
